### ISSUE TITLE
Menú de inicio.

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIQ_2021-tupmtaller#1]
**Fecha:** 26 de Marzo.

**Comment by ismaelsaiz** [comment]
#include <stdio.h>
 
 int main(){
 
 
 int opcion, n;
 
printf ("Bienvenidos a la pagina oficial de tupmtaller.\n");
    
    	//Pedimos la opcion al usuario
    	
        printf( "1. Registrarse.\n");
        printf( "2. Iniciar sesion.\n");
        printf( "3. Salir.\n");

        do
        {
            printf( "Introduzca opcion (1-3):\n");
            scanf( "%d", &opcion);

        } while ( opcion < 1 || opcion > 3 );
        

        switch ( opcion )
        {
            case 1: printf("Registre su nombre de usuario\n");
                    scanf("%d", &n);
            
                    printf("Escriba su clave nueva\n");
                    scanf("%d", &n);
                    
                    break;

            case 2: printf("Escriba su nombre de usuario\n");
                    scanf("%d", &n);
                    
                     printf("Escriba su clave\n");
                     scanf("%d", &n);
            
                    break;

            case 3: printf("Esperemos volver a verte pronto\n");
            
                   break;
            
         }

    while ( opcion != 4 );

    return 0;
}

**Comment by ismaelsaiz** [comment]
Buenas, tenemos una duda porque al poner el case 1, nos deja poner el nombre de usuario, pero la contraseña no. Ahí está subido el código.


Un saludo
